# Generated by Django 3.1 on 2020-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrument_text',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='band_text',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='firstname_text',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='lastname_text',
            new_name='lastname',
        ),
    ]
