# Generated by Django 3.1 on 2020-08-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20200806_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='added_date',
        ),
    ]
